try {
  console.log(a + b);
} catch (err) {
  console.log("Error example");
}

throw new TypeError();
